### ISSUE TITLE
ignored no data for data_aux tiles

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#20]
Problem: 
* slope and elevation vrt (created from tiles) have nodata on top of data (see figure)

Elevation with no data masking valid data
![Relative Elevation](https://user-images.githubusercontent.com/4864803/143422925-ef5e59b3-d506-462f-acb3-f98dddc68711.png)

PlanetScope data
![PlanetScope](https://user-images.githubusercontent.com/4864803/143422619-96fe878d-4dd1-4fba-bf34-aba0bde5d335.png)

**Comment by initze** [comment]
That shellscript will make it work!
```
ls /isibhv/projects/p_aicore/AICORE/arcticDEM_inference_grid/data_aux/ArcticDEM/tiles_rel_el/*.tif > flist_rel_el.txt;
ls /isibhv/projects/p_aicore/AICORE/arcticDEM_inference_grid/data_aux/ArcticDEM/tiles_slope/*.tif > flist_slope.txt;
gdalbuildvrt -input_file_list flist_rel_el.txt -srcnodata "0" -vrtnodata "0" elevation.vrt;
gdalbuildvrt -input_file_list flist_slope.txt -srcnodata "nan" -vrtnodata "0" slope.vrt;
```

**Comment by khdlr** [comment]
Great! Does that mean that this is an inherent problem in the vrt, or is there still something we can do to future-proof our code?

**Comment by initze** [comment]
yeah,
this was more a data specific problem of the ArcticDEM exports and vrt creation.

I was just wondering if we create a subdir for little helper scripts. However, they might be quite specific.

**Comment by khdlr** [comment]
Good to know. Yeah, let's introduce a `scripts` directory or for useful command line snippets.
