### ISSUE TITLE
Clean up after run and prepare for new one

### ISSUE THREAD

**Issue by khdlr** [initze/thaw-slump-segmentation#5]
It would be good to have a script that cleans up after the end of the run. That means for example to pack all used files, configurations and results into a folder or a file (e.g. .zip). Then you don't have to delete everything by hand, you don't forget anything and you can continue with other data. 
This may as well involve the option to make another run with a new configuration on the same data cleaning up the files which aren't needed or can lead to confusion.
Ofc only if you run the cleanup-script explicitly.
The current constellation (folder name: timestamp) can be kept as it is very usefull, I can just imagine that sometime in the future it might come in handy to have a "reset" function.

**Comment by initze** [comment]
deprecated!
