### ISSUE TITLE
add NDVI/Indices

### ISSUE THREAD

**Issue by initze** [initze/thaw-slump-segmentation#59]
* add NDVI as dataset
* use more indices?

**Comment by khdlr** [comment]
I believe it would be good to calculate NDVI/other indices when loading the data instead of hard-baking them into the data cubes, what are your thoughts on this?

**Comment by initze** [comment]
Sounds reasonable.
I guess this can be triggered once NDVI appears in the dataset in the config file. Should be very fast to create on the fly I guess.
Adding some more indices would be somehow cool. However we need to define the band numbers and run some validity hchecks for the dataset types
S2 e.g used Bands 8 and 4
Plane uses 4 and 3
S1 does not support it ...

**Comment by initze** [comment]
implemented with [ce443cd](https://github.com/initze/thaw-slump-segmentation/commit/ce443cd50b1be0e6feb421da5e267646e1727f01) for PlanetScope images

**Comment by initze** [comment]
completed for "s2"
[9a545b3](https://github.com/initze/thaw-slump-segmentation/commit/9a545b3cfc0236491cd282179d2f748b0b9137e3)
